// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_marssTMB_TMBExports
#include <TMB.hpp>
#include "dfa.hpp"
#include "marss.hpp"
#include "marss2.hpp"
#include "marxss.hpp"
#include "uni.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "dfa") {
    return dfa(this);
  } else if(model == "marss") {
    return marss(this);
  } else if(model == "marss2") {
    return marss2(this);
  } else if(model == "marxss") {
    return marxss(this);
  } else if(model == "uni") {
    return uni(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
